name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: LarchLiu/actions-save-files@v1.0.3
      with:
        github_token: ${{ github.token }}
        publish_dir: ./
